### ISSUE TITLE
Can you use this in an Azure Pipeline?

### ISSUE THREAD

**Issue by mec07** [development-bizeta-mestre/nsis-extension#17]
Hi,

This is where the Q&A link on https://marketplace.visualstudio.com/items?itemName=bizeta.nsis-task&ssr=false#qna sent me, so I'm asking here. Can this be used in an Azure Pipeline? If so, how do you use it in the pipeline?

I've switched from AWS Codepipeline to Azure Pipeline because my new code signing certificate lives in Azure Key Vault. In AWS Codepipeline I just stored the makensis.exe in my repo and used it to compile the installers (i.e. `./makensis.exe /V1 "$(scriptname)"` ). Azure Pipeline is blocking the execution of the binary for security reasons, but I found this plugin which seems like it could be used. 

If it can indeed be used in Azure Pipeline, is there any chance you could provide an example of the yaml that is required and any additional setup steps required to get the pipeline to see this extension? There is some information in the readme, but it wasn't clear to me what I need to put to make it work.

One other thing that wasn't exactly clear to me was what you meant by the following:

> Include NSIS as an environnement variable called NSIS_EXE that you can use in the following tasks. 

Do you mean this?
```
variables:
  - name: NSIS
    value: NSIS_EXE
```

Thanks for the help!

**Comment by mec07** [comment]
@development-bizeta-mestre or @tomap do you know the answer to this?

**Comment by development-bizeta-mestre** [comment]
Hi @mec07, 

Yes this plugin can be used in azure pipeline, please check the sample code below:

```
  - task: bizeta.nsis-task.796c90b1-9f8c-424a-b03b-b789bb5945d3.nsis@2
    displayName: Nsis
    inputs:
      scriptFile: '{absolute-path-to-your-script}.nsi'
      arguments: '/V3 /DDISTDIR="{absolute-path-to-your-build-output}"'
      includeMorePlugins: yes 
      includeCustomPlugins: yes
      includeCustomPluginsPath: '{absolute-path-to-your-plugins-folder}'	 
```
- includeMorePlugins : yes | no, if you want to include the default plugins provided with task. Follow this link to check what they are: https://github.com/development-bizeta-mestre/nsis-extension/tree/master/nsis/plugins 
- includeCustomPlugins : yes | no, if you want to include more plugins that aren't provided as default, must be 'yes' if you want include your plugins
- includeCustomPluginsPath : https://github.com/development-bizeta-mestre/nsis-extension#custom-plugins-path
